name: mlff
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pip
  - pandas
  - scikit-learn
  - wandb
  - pip:
      - schnetpack
      - dscribe
      - nequip==0.16.0
      - git+https://github.com/mir-group/allegro.git@v0.8.0